In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 44.9 MB/s  0:00:006m0:00:01
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 52.8 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

# Step 1. Data understanding：

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("stock_data_350.csv")
df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values(["Ticker", "Date"])

# keep recent 5 years
df = df[df["Date"] >= "2020-01-01"].copy()

In [13]:
df

,Date,Ticker,Open,High,Low,Close,Adj Close,Volume
0,2020-01-02,A,85.900002,86.349998,85.199997,85.949997,82.210464,1410500.0
1,2020-01-03,A,84.669998,85.330002,84.500000,84.570000,80.890480,1118300.0
2,2020-01-06,A,84.000000,84.820000,83.599998,84.820000,81.129623,1993200.0
3,2020-01-07,A,83.959999,85.260002,83.940002,85.080002,81.378319,1684700.0
4,2020-01-08,A,85.959999,86.470001,85.199997,85.919998,82.181763,1847600.0
...,...,...,...,...,...,...,...,...
433658,2024-12-24,XOM,106.519997,107.190002,105.699997,106.400002,101.953667,7807000.0
433659,2024-12-26,XOM,106.519997,107.029999,105.940002,106.489998,102.039902,9652400.0
433660,2024-12-27,XOM,106.300003,107.989998,105.769997,106.480003,102.030327,11943900.0
433661,2024-12-30,XOM,106.300003,106.559998,105.510002,105.760002,101.340408,11080800.0
433662,2024-12-31,XOM,106.169998,107.900002,105.779999,107.570000,103.074768,12387800.0

In [14]:
df.shape

(433663, 8)

In [15]:
df.columns

Index(['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume'],
      dtype='str')

In [16]:
df.dtypes

Date         datetime64[us]
Ticker                  str
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume              float64
dtype: object

In [17]:
df.head()

,Date,Ticker,Open,High,Low,Close,Adj Close,Volume
0,2020-01-02,A,85.900002,86.349998,85.199997,85.949997,82.210464,1410500.0
1,2020-01-03,A,84.669998,85.330002,84.500000,84.570000,80.890480,1118300.0
2,2020-01-06,A,84.000000,84.820000,83.599998,84.820000,81.129623,1993200.0
3,2020-01-07,A,83.959999,85.260002,83.940002,85.080002,81.378319,1684700.0
4,2020-01-08,A,85.959999,86.470001,85.199997,85.919998,82.181763,1847600.0

In [18]:
df["Date"].min(), df["Date"].max()
df["Ticker"].nunique()
df["Ticker"].unique()[:10]

<StringArray>
['A', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM']
Length: 10, dtype: str

In [20]:
df.isnull().sum()

Date         0
Ticker       0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.groupby("Ticker").size().describe()

count     346.000000
mean     1253.361272
std        50.392599
min       513.000000
25%      1258.000000
50%      1258.000000
75%      1258.000000
max      1258.000000
dtype: float64

In [23]:
df.groupby("Ticker").size().sort_values().head(10)

Ticker
GEHC     513
CEG      742
ABNB    1020
OTIS    1205
CARR    1205
TSLA    1258
TMUS    1258
TGT     1258
T       1258
STZ     1258
dtype: int64

In [24]:
df[["Open", "High", "Low", "Close", "Adj Close", "Volume"]].describe()

,Open,High,Low,Close,Adj Close,Volume
count,433663.000000,433663.000000,433663.000000,433663.000000,433663.000000,4.336630e+05
mean,148.554354,150.309311,146.766184,148.561315,140.953857,8.036504e+06
std,183.887562,185.956816,181.758246,183.910249,181.712072,3.010858e+07
min,4.040000,4.160000,3.800000,4.010000,3.009994,0.000000e+00
25%,54.970001,55.639999,54.230000,54.950001,49.535585,1.198500e+06
50%,99.209999,100.430000,97.989998,99.190002,92.491440,2.568000e+06
75%,181.929993,184.059998,179.679993,181.886864,171.260925,6.094250e+06
max,3369.000000,3416.709961,3345.439941,3370.270020,3370.270020,1.543911e+09

# Step 2. Data cleaning：

# Step 3. Feature engineering：

# Step 4. Exploratory analysis：

# Step 5. Preprocessing for clustering：

# Step 6. Clustering：

# Step 7. Cluster interpretation：